/**
 * @author              Nathan M. Degineh - N8
 * @name                Gen Node
 * @module              index.js
 * @description         Default config file
 * @kind                Config
 * @copyright           September 2018 Gen Node
 */

module.exports = {

    models                  : [],
    serviceName             : 'GenNode Server', //
    serviceDescription      : `Generated by genNode : ${new Date().getFullYear()}`,
    author                  : 'GenNode',
    copyright               : `Copyright : ${new Date().getFullYear()}`,
    repoURL                 : "http://github.com",
    licence                 : 'MIT', // The MIT License
    version                 : '0.0.1', // First alpha release
    baseURL                 : '/service',

    dependantServices       : {
        endPoints               : [],
        abortIfFail             : false
    },

    environment             : {
        DEBUG                   : "*",
        PORT                    : 3300,
        MODE                    : "test_mode",
        MONGODB_URL             : "mongodb://localhost:27017/service",
        REVERSE_PROXY           : "http://localhost",
        COLLECTION_RETURN_SIZE  : "24",
        ELEMENT_IN_PAGE         : "12",
        ELASTIC_SEARCH_URL      : "http://localhost:9200"
    },

    // Defines authentication header key and type for api requests
    authentication          : {
        type        : 'Bearer',
        headerKey   : 'Authentication'
    },

    requireAuthentication   : {
        all : false,
        accessLevel : null
    },

    includeApiReqLib        : true, // If true will include library for requesting outside api call
    certificate             : {
        root        : null,
        client      : null,
        clientKey   : null
    }, // Some path to a certificate if request will be made using https.

    // Defines related containers
    // elasticSearch           : true,
    mongodb                 : true,
    nginx                   : true,
    docker                  : true,
    jenkins                 : true,
    postman                 : true,
    enableProxy             : true,
    test                    : true,
    documentation           : true,
    readMe                  : true,
    commit                  : true,
    // commitMessage           : 'Initial commit by gennode.',
    runServer               : false,
};

