/**
 * @author              __author__
 * @name                __serviceName__
 * @module              errorCodes.js
 * @description         Error code constants.
 * @kind                Constants
 * @copyright           __copyright__
 */

/**
 * @description     - Defines error codes.
 */
module.exports = {

    /**
     * @name            - SEC (Shared error Codes)
     * @description     - Defines a list of error codes that could be generated by all services. (Shared Error Codes)
     */
    SEC                 : {

        CREATOR_SERVICE_UNKNOWN             : {
            errorCode       : "SEC_000",
            errorName       : "Service Unknown value",
            errorMessage    : "Creator service is not known",
            hint            : "Possible problem could arise in using old service id's.View documentation for the latest values."
        },

        CAST_ERROR                          : {
            errorCode       : "SEC_001",
            errorName       : "Cast error",
            errorMessage    : "Possible casting error.",
            hint            : "View documentation for proper value types.This error usually arises when using objectId values."
        },

        SERVER_SIDE_ERROR                   : {
            errorCode       : "SEC_002",
            errorName       : "Server side error",
            errorMessage    : "Server side error.",
            hint            : "This is error code will be sent when all server side error codes are exhausted. Try again latter or contact service provider."
        },

        NO_DATA_FOUND                       : {
            errorCode       : "SEC_003",
            errorName       : "No data found",
            errorMessage    : "No data found in query.",
            hint            : "The query data you provided may have been removed, or do not exist in the first place."
        },

        IMPROPER_DATA                       : {
            errorCode       : "SEC_004",
            errorName       : "Improper data",
            errorMessage    : "Proper data was not provided.",
            hint            : `Cross check proper data against values in documentation`
        },

        SERVICES_DOWN                       : {
            errorCode       : "SEC_005",
            errorName       : "Service down",
            errorMessage    : "Some dependent services may be down.",
            hint            : "Contact service provider."
        },

        QUERY_ERROR                         : {
            errorCode       : "SEC_006",
            errorName       : "Query error",
            errorMessage    : "Error while querying",
            hint            : "Nothing you can do, try again latter or contact service provider."
        },

        VALIDATION_ERROR                    : {
            errorCode       : "SEC_007",
            errorName       : "Validation error",
            errorMessage    : "You have not provided complete data.",
            hint            : "View documentation for necessary fields."
        },

        NO_QUERY_DATA                       : {
            errorCode       : "SEC_008",
            errorName       : "No query data provided",
            errorMessage    : "No proper or no query data has been provided.Mainly could be caused by using wrong key in url.",
            hint            : "View documentation for proper key to use in query and proper query value."
        },

        OPERATION_METHOD_INVALID            : {
            errorCode       : "SEC_009",
            errorName       : "Invalid collection operation method.",
            errorMessage    : "Proper collection operation method have not been provided.",
            hint            : "View documentation for valid operation methods."
        },

        CONNECTION_REFUSED                  : {
            errorCode       : "SEC_010",
            errorName       : "Connection refused",
            errorMessage    : "Internal service connection refused.",
            hint            : "Observe ping results at app init. and check if you have allowed the service to start if the dependant services are down."
        },

        CONNECTION_ABORTED                  : {
            errorCode       : "SEC_011",
            errorName       : "Connection aborted",
            errorMessage    : "Internal service connection aborted.",
            hint            : "Ping dependent services, dependent services may be down."
        },

        CONNECTION_CANCELED                 : {
            errorCode       : "SEC_012",
            errorName       : "Connection canceled",
            errorMessage    : "Internal service connection canceled.",
            hint            : "Could be caused due probable timeout. View documentation for timeout setting."
        },

        NOT_PROPER_OBJECT_ID                : {
            errorCode       : "SEC_014",
            errorName       : "Not proper objectId",
            errorMessage    : "Provided value can not be casted to objectId.",
            hint            : "View documentation for proper objectId formats."
        },

        UN_MATCHED_ENDPOINT                 : {
            errorCode       : "SEC_015",
            errorName       : "Un-matched endpoint",
            errorMessage    : "You have requested for an unmatched endpoint.",
            hint            : "View documentation for a list of endpoints."
        },

        PHONE_DOES_NOT_MATCH_EXPRESSION     : {
            errorCode       : "SEC_016",
            errorName       : "Phone does not match expression",
            errorMessage    : "Input phone value does not match phone expression",
            hint            : "View documentation for proper phone expressions."
        },

        DEPENDENT_SERVICES_DOWN             : {
            errorCode       : "SEC_017",
            errorName       : "Dependant services down",
            errorMessage    : "Dependant services may be down.",
            hint            : "Contact your service provider if there is any change in the access url."
        }

    },

    /**
     * @name            - Authentication error codes.
     * @description     - Defines a list of error codes that could be generated when communicating with authentication service.
     */
    AUT                 : {

        AUTHENTICATION_NOT_SET                  : {
            errorCode       : "AUT_000",
            errorName       : "Authentication is not set",
            errorMessage    : "Authentication values are not set.",
            hint            : "View documentation on how to set authentication values on the header."
        },

        AUTHENTICATION_DATA_NOT_PROPER_LENGTH   : {
            errorCode       : "AUT_001",
            errorName       : "Authentication data not proper length.",
            errorMessage    : "Authentication data does not contain proper length.",
            hint            : "View documentation on how to set authentication values on the header."
        },

        AUTHENTICATION_TYPE_NOT_ACCORD          : {
            errorCode       : "AUT_002",
            errorName       : "Authentication type is not correct.",
            errorMessage    : "Authentication type is not according to constants.",
            hint            : "Authentication type should be 'Bearer', view documentation for more."
        },

        AUTHENTICATION_VALUE_NOT_SET            : {
            errorCode       : "AUT_003",
            errorName       : "Authentication value is not set",
            errorMessage    : "Authentication values are not set.",
            hint            : "Authentication key exists, but value may not."
        },

        AUTHENTICATION_SERVICE_ACCESS_FAIL      : {
            errorCode       : "AUT_004",
            errorName       : "Authentication access fail",
            errorMessage    : "Failed to access authentication service.",
            hint            : "Ping authentication service, or contact service provider."
        },

        TOKEN_REVOKED                           : {
            errorCode       : "AUT_005",
            errorName       : "Token revoked",
            errorMessage    : "Token is revoked.",
            hint            : "Consider logging in again."
        },

        TOKEN_EXPIRED                           : {
            errorCode       : "AUT_006",
            errorName       : "Token expired",
            errorMessage    : "Token has expired.",
            hint            : "Consider logging in again."
        },

        AUTHORIZED_SERVICE_ACCESS_DENIED        : {
            errorCode       : "AUT_007",
            errorName       : "Authorized service_access denied",
            errorMessage    : "Service has no been granted access",
            hint            : "View documentation which services are allowed to access which services.Contact service provider for more."
        },

        SERVICE_ACCESS_DENIED                   : {
            errorCode       : "AUT_008",
            errorName       : "Service access denied",
            errorMessage    : "Service has no been granted access",
            hint            : "View documentation which services are allowed to access which services.Contact service provider for more."
        },

        UNAUTHORIZED_ACCESS                     : {
            errorCode       : "AUT_009",
            errorName       : "Unauthorized token",
            errorMessage    : "Token is not authorized to access this route.",
            hint            : "View documentation for access level"
        }

    }

};
